{% set name = "atlasclient" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f602bad97e47299f996344b92c8b01dc363f3eb643770f676472bcdb2b59596e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six >=1.11.0
    - click >=6.0
    - requests >=2.18.4

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - atlasclient
    - atlasclient.base
    - atlasclient.client
    - atlasclient.events
    - atlasclient.exceptions
    - atlasclient.models
    - atlasclient.utils
  commands:
    - pip check

about:
  home: https://github.com/jpoullet2000/atlasclient
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Atlas client in Python
  description: |
    **Apache Atlas client in Python**

    Only compatible with Apache Atlas REST API v2.

    Free software: Apache Software License 2.0
    [Documentation](https://atlasclient.readthedocs.io)

    **Features**

    Lazy loading: requests are only performed when data are required and not yet available
    Resource object relationships: REST API from sub-resources are done transparently for the user,
    for instance the user does not have to know that it needs to trigger a different REST
    request for getting the classifications of a specific entity.

  doc_url: https://atlasclient.readthedocs.io/
  dev_url: https://github.com/jpoullet2000/atlasclient

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
